### ISSUE TITLE
Why not add more language training data such as Wukong dataset?

### ISSUE THREAD

**Issue by lucasjinreal** [Beckschen/ViTamin#1]
Why not add more language training data such as Wukong dataset?

**Comment by Beckschen** [comment]
Thank you for your interest! Our models are trained on DataComp-1B, which is well-filtered and better suited for benchmarking models.

**Comment by lucasjinreal** [comment]
It's good to see your work uses less data then siglip while got a comparable result. 

Am really looking forward to see if it can even stronger with more data. Neverthless, from a practical aspect of view, if a multilanguage  vision encoder pretrained on various dataset could be even better, except for current strongest target for benchmarking purpose. 

Did u guys have any plan to add more Chinese pretrain data and release a Chinese optimized version?

**Comment by Beckschen** [comment]
Thank you for responding! Our training process is completely transparent given the publicly accessible dataset and fully-released code.  We have made our training code available, and we encourage the community to utilize it to train our proposed ViTamin model for various purposes. Certainly a multilanguage encoder is great in terms of the broad use cases in VLMs and multi-modal LLMs and we hope we have the bandwidth to do it in the future!

**Comment by lucasjinreal** [comment]
Thank you for sharing the code openly. Could you tell us approximately how much computational resource and time would be required to continue training on datasets like Wukong? Also, is there a strategy to prevent catastrophic forgetting when updating the model?

**Comment by vishaal27** [comment]
Just wanted to share this preprint in which we studied continual pretraining in detail, including strategies to prevent catastrophic forgetting, looking forward to hearing your feedback: https://arxiv.org/abs/2408.14471
