### ISSUE TITLE
Why not taking this method to accerate training？ FLIP

### ISSUE THREAD

**Issue by lucasjinreal** [Beckschen/ViTamin#5]
https://arxiv.org/abs/2212.00794

**Comment by Beckschen** [comment]
Hello thanks for your interest! We follow the training scheme as DataComp did to have a fair comparison, so we haven't applied masking.

**Comment by lucasjinreal** [comment]
Hi, I still wonna ask a little question.

Have consider using next token prediction to train the ViT, not constractive learning. Do u find any work did this method?

**Comment by Beckschen** [comment]
Thanks, that is a really interesting question. Yet we haven't experimented in the manner of next token prediction.
