### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ericyq** [Beckschen/ViTamin#8]
>>>tokenizer = open_clip.get_tokenizer('hf-hub:laion/CLIP-ViT-L-14-DataComp.XL-s13B-b90K')

ViTamin/ViTamin/open_clip/factory.py", line 92, in get_tokenizer
    context_length = get_model_config(model_name)['text_cfg']['context_length']
TypeError: 'NoneType' object is not subscriptable

**Comment by Beckschen** [comment]
Hello, have you followed the [installation instruction](https://github.com/Beckschen/ViTamin/blob/main/ViTamin/README.md)?
